POST http://localhost:3001/api/logout
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImvDpHl0dMOkasOkQGvDpHl0dGlzLmNvbSIsImlkIjoxLCJpYXQiOjE2Mzc5OTI2ODN9.uAJrCy1jIUeENe21s7iqzu9neC483wjHMzmoWPp0U_A